### ISSUE TITLE
filterwarnings("ignore") turns off all warnings in downstream code

### ISSUE THREAD

**Issue by rly** [LorenFrankLab/track_linearization#2]
This line turns off all warnings in the current python execution, including in all downstream code, like spyglass, which imports track_linearization, and in notebook cells after importing track_linearization or spyglass. Is this necessary and can it be removed? Thanks.

https://github.com/LorenFrankLab/track_linearization/blob/4c4d8bd880f6d8d63a55a12ea37801af10d9b3df/track_linearization/core.py#L10

**Comment by rly** [comment]
cc @khl02007

**Comment by edeno** [comment]
Fixed by efba540bdfc0389a43f8a4a93549a6b1251601c1

**Comment by rly** [comment]
Thanks!!
